export const BOOKING_CREATED_NOTIFICATION_TYPE = 'BOOKING_CREATED';
export const CLASS_REMINDER_NOTIFICATION_TYPE = 'CLASS_REMINDER';
export const CLASS_CANCELED_NOTIFICATION_TYPE = 'CLASS_CANCELED';
export const CLASS_RESCHEDULED_NOTIFICATION_TYPE = 'CLASS_RESCHEDULED';

export type NotificationJobType =
  | typeof BOOKING_CREATED_NOTIFICATION_TYPE
  | typeof CLASS_REMINDER_NOTIFICATION_TYPE
  | typeof CLASS_CANCELED_NOTIFICATION_TYPE
  | typeof CLASS_RESCHEDULED_NOTIFICATION_TYPE;
